apiVersion: v1
kind: Service
metadata:
  name: sample-api
  namespace: platformops
  labels:
    app.kubernetes.io/name: sample-api
    app.kubernetes.io/part-of: platformops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sample-api
  ports:
    - name: http
      port: 80
      targetPort: http
