name: sample-api
namespace: platformops
image: sample-api
tag: local
replicas: 2

ports:
  container: 8080
  service: 80

health:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 15

resources:
  cpuRequest: 100m
  memoryRequest: 128Mi
  cpuLimit: 500m
  memoryLimit: 512Mi

env:
  APP_ENV: local
